title: <p align="center">Marc Huai</p>

logo: "/assets/img/HeadShot.jpg"

description: |
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/marchuai/">LinkedIn</a> |
  <a href="https://github.com/marc-huai">GitHub</a>
  </p>

  <p align="justify">
  I am a Data Engineer with a strong foundation in applied mathematics and computer programming, currently advancing my skills through an intensive Data Engineering Bootcamp at Washington University in St. Louis.
  <br><br>
  I specialize in advanced SQL, data pipeline development, cloud data platforms, and big data technologies. I thrive on solving complex problems and making data more accessible and actionable.
  <br><br>
  My passion lies in transforming large, disconnected data sets into valuable insights that drive business decisions. I excel in creating unified data systems that enhance data reliability and usability.
  <br><br>
  With experience leading data projects, resolving complex challenges, and executing smooth, accurate data migrations, I bring strong value to any data-driven team.
  </p>

theme: jekyll-theme-minimal

google_analytics: G-JHVECBZSDN
