title: <p align="center">Marc Huai</p>

logo: "/assets/img/HeadShot.jpg"

description: |
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/marchuai/">LinkedIn</a> |
  <a href="https://github.com/marc-huai">GitHub</a>
  </p>

  <p align="justify">
  Data Engineer with a strong foundation in math and programming, currently sharpening my skills through a Data Engineering Bootcamp at Washington University in St. Louis.
  <br><br>
  I specialize in SQL, data pipelines, and cloud platforms—passionate about turning complex data into actionable insights and building reliable, unified data systems.
  </p>

theme: jekyll-theme-minimal

google_analytics: G-JHVECBZSDN
